# Introduction

Will test a Langchain SQLAgent as tool and a quantized Llama 2 model (from Kaggle). The objective is to see if we can use such a quantized model to replace OpenAI for SQL databases exploration.

# Install and import packages

In [1]:
!pip install -q -U langchain
!pip install -q -U transformers
!pip install -q -U accelerate
!pip install -q -U bitsandbytes

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
cuml 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
dask-cudf 23.8.0 requires cupy-cuda11x>=12.0.0, which is not installed.
apache-beam 2.46.0 requires dill<0.3.2,>=0.3.1.1, but you have dill 0.3.7 which is incompatible.
apache-beam 2.46.0 requires pyarrow<10.0.0,>=3.0.0, but you have pyarrow 11.0.0 which is incompatible.
cudf 23.8.0 requires pandas<1.6.0dev0,>=1.3, but you have pandas 2.0.2 which is incompatible.
cudf 23.8.0 requires protobuf<5,>=4.21, but you have protobuf 3.20.3 which is incompatible.
cuml 23.8.0 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
dask-cuda 23.8.0 requires dask==2023.7.1, but you have dask 2023.9.0 which is incompatible.
dask-cuda 23.8.0 requires pandas<1.6.0dev0,>=1.3, but 

In [2]:
!pip install torch==2.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.2/670.2 MB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 50.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 52.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 67.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 22.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━

In [3]:
import torch
from transformers import pipeline
from langchain.llms import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForCausalLM
from langchain.agents import create_sql_agent 
from langchain.agents.agent_toolkits import SQLDatabaseToolkit 
from langchain.sql_database import SQLDatabase 
from langchain.agents import AgentExecutor 
from langchain.agents.agent_types import AgentType
from time import time

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
torch.__version__

'2.1.0+cu121'

# Setup the database connection

In [5]:
custom_table_info = {
    "artists": """CREATE TABLE artists2 (
        artist_id integer NOT NULL,
        name character varying(200),
        nationality character varying(50),
        gender character varying(25),
        birth_year integer,
        death_year integer,
        CONSTRAINT artists_pk PRIMARY KEY (artist_id))

/*
3 rows from artists table:
"artist_id"	"name"	"nationality"	"gender"	"birth_year"	"death_year"
12	"Jüri Arrak"	"Estonian"	"Male"	1936	
19	"Richard Artschwager"	"American"	"Male"	1923	2013
22	"Isidora Aschheim"	"Israeli"	"Female"		
*/""",
    "artworks": """CREATE TABLE artworks (
        artwork_id integer NOT NULL,
        title character varying(500),
        artist_id integer NOT NULL,
        name character varying(500),
        date integer,
        medium character varying(250),
        dimensions text,
        acquisition_date text,
        credit text,
        catalogue character varying(250),
        department character varying(250),
        classification character varying(250),
        object_number text,
        diameter_cm text,
        circumference_cm text,
        height_cm text,
        length_cm text,
        width_cm text,
        depth_cm text,
        weight_kg text,
        durations integer,
        CONSTRAINT artworks_pk PRIMARY KEY (artwork_id))

/*
3 rows from artworks table:
"artwork_id"	"title"	"artist_id"	"name"	"date"	"medium"	"dimensions"	"acquisition_date"	"credit"	"catalogue"	"department"	"classification"	"object_number"	"diameter_cm"	"circumference_cm"	"height_cm"	"length_cm"	"width_cm"	"depth_cm"	"weight_kg"	"durations"
102312	"Watching the Game"	2422	"John Gutmann"	1934	"Gelatin silver print"	"9 3/4 x 6 7/16' (24.8 x 16.4 cm)"	"2006-05-11"	"Purchase"	"N"	"Photography"	"Photograph"	"397.2006"			"24.8"		"16.4"			
103321	"Untitled (page from Sump)"	25520	"Jerome Neuner"	1994	"Page with chromogenic color print and text"	"12 x 9 1/2' (30.5 x 24.1 cm)"	"2006-05-11"	"E.T. Harmax Foundation Fund"	"N"	"Photography"	"Photograph"	"415.2006.12"			"30.4801"		"24.13"			
10	"The Manhattan Transcripts Project, New York, New York, Episode 1: The Park"	7056	"Bernard Tschumi"		"Gelatin silver photograph"	"14 x 18' (35.6 x 45.7 cm)"	"1995-01-17"	"Purchase and partial gift of the architect in honor of Lily Auchincloss"	"Y"	"Architecture & Design"	"Architecture"	"3.1995.11"			"35.6"		"45.7"			
*/""",
}

In [6]:
sqlite_path = "/kaggle/input/moma-db/moma.db"
sqlite_uri = f"sqlite:///{sqlite_path}"
db = SQLDatabase.from_uri(sqlite_uri,custom_table_info = custom_table_info)

In [7]:
db.run("select count(*) from artists")

'[(15544,)]'

# Intialize the model

In [8]:
access_token = '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'

In [9]:
model_id = 'meta-llama/Llama-2-7b-chat-hf'
time_1 = time()
tokenizer = AutoTokenizer.from_pretrained(model_id,use_auth_token = access_token  )
model_name = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,use_auth_token = access_token
    )
print(f"Tokenizer & pipeline: {round(time() - time_1)} sec.")

/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py:732: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:468: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(


config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

Tokenizer & pipeline: 121 sec.


# Test the model

Let's wrap the model into a HuggingFace pipeline.

In [10]:
#stop_words_ids = [tokenizer.encode(stop_word) for stop_word in ["foo", "bar"]]

In [11]:
#stop_words_ids

In [12]:
from transformers import StoppingCriteria, StoppingCriteriaList

In [13]:
class StoppingCriteriaSub(StoppingCriteria):

    def __init__(self, stops = []):
      StoppingCriteria.__init__(self), 

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, stops = []):
      self.stops = stops
      for i in range(len(stops)):
        self.stops = self.stops[i]

In [14]:
def custom_stopping_criteria(input_ids: torch.LongTensor, score: torch.FloatTensor, **kwargs) -> bool:
    return True#your_condition

stopping_criteria = StoppingCriteriaList([custom_stopping_criteria])


In [15]:
stopping_criteria[0]

<function __main__.custom_stopping_criteria(input_ids: torch.LongTensor, score: torch.FloatTensor, **kwargs) -> bool>

In [16]:
class StoppingCriteriaSub(StoppingCriteria):

    def __init__(self, stops = [], encounters=1):
        super().__init__()
        self.stops = [stop.to("cuda") for stop in stops]

    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:
        for seq in input_ids:
            for stop in self.stops:
                if len(seq) >= len(stop) and torch.all((stop == seq[-len(stop):])).item():
                    return True
        return False


stop_words = ["Question:"," Question:",".\n\nQuestion:","\n\nQuestion:"," \n\nQuestion:", " \nQuestion:", " \n\n","Question" ]#["\nQuestion:", "<bot>:"]
stop_words_ids = [tokenizer(stop_word, return_tensors='pt')['input_ids'].squeeze() for stop_word in stop_words]
stopping_criteria2 = StoppingCriteriaList([StoppingCriteriaSub(stops=stop_words_ids)])

In [17]:
stop_words = ["Question","Question:"," Question:",".\n\nQuestion:","\n\nQuestion:"," \n\nQuestion:", " \nQuestion:", " \n\n", ]#["\nQuestion:", "<bot>:"]
stop_words_ids = [tokenizer(stop_word, return_tensors='pt')['input_ids'].squeeze() for stop_word in stop_words]
stopping_criteria2 = StoppingCriteriaList([StoppingCriteriaSub(stops=stop_words_ids)])

In [18]:
#[tokenizer(stop_word, return_tensors='pt')['input_ids'].squeeze() for stop_word in _DEFAULT_TEMPLATE.split()][-10:]

In [19]:
tokenizer.decode(torch.tensor([     1,  313, 4176, 3010,  467]))

'<s> (SQLQuery).'

In [20]:
tokenizer.decode(torch.tensor([    1,   894, 29901]))

'<s> Question:'

In [21]:
stop_words_ids

[tensor([  1, 894]),
 tensor([    1,   894, 29901]),
 tensor([    1, 29871,   894, 29901]),
 tensor([    1,   869,    13,    13, 16492, 29901]),
 tensor([    1, 29871,    13,    13, 16492, 29901]),
 tensor([    1,   259,    13,    13, 16492, 29901]),
 tensor([    1,   259,    13, 16492, 29901]),
 tensor([  1, 259,  13,  13])]

In [22]:
#stop_list = [".\n\nQuestion:","\n\nQuestion:"," \n\nQuestion:", " \nQuestion:", " \n\n", ]
stop_token_ids = [tokenizer(x,  return_tensors='pt', add_special_tokens=False)['input_ids'] for x in stop_words]
stop_token_ids = [torch.LongTensor(x) for x in stop_token_ids]


class StopOnTokens(StoppingCriteria):
    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> bool:
        for stop_ids in stop_token_ids:
            print(f"Testing {input_ids[0][-len(stop_ids[0])+1:]} against {stop_ids[0][1:]}")
            if eq(input_ids[0][-len(stop_ids[0])+1:], stop_ids[0][1:]).all():
                return True
        return False


stopping_criteria3 = StoppingCriteriaList([StopOnTokens()])

In [23]:
tokenizer.eos_token

'</s>'

In [24]:
from transformers import StoppingCriteria, StoppingCriteriaList
from torch import cuda, LongTensor, FloatTensor

def create_stopping_criteria(stop_words, tokenizer, device):

    class StoppingCriteriaSub(StoppingCriteria):
        def __init__(self, stops = [], device=device, encounters = 1):
            super().__init__()
            self.stops = stops = [stop.to(device) for stop in stops]

        def __call__(self, input_ids: LongTensor, scores: FloatTensor) -> bool:
            last_token = input_ids[0][-1]
            for stop in self.stops:
                if tokenizer.decode(stop) == tokenizer.decode(last_token):
                    return True
            return False

    stop_word_ids = [tokenizer(stop_word,
                               return_tensors="pt", 
                               add_special_tokens=False)["input_ids"].squeeze() 
                               for stop_word in stop_words]

    stopping_criteria = StoppingCriteriaList([StoppingCriteriaSub(stops=stop_word_ids)])
    return stopping_criteria

device = f'cuda:{cuda.current_device()}' if cuda.is_available() else 'cpu'
stop_words_list = ["Question","Question:"," Question:",".\n\nQuestion:","\n\nQuestion:"," \n\nQuestion:", " \nQuestion:", " \n\n", ]#["QUESTION:"]
stopping_criteria5 = None
if stop_words_list is not None:
    stopping_criteria5 = create_stopping_criteria(stop_words_list, tokenizer, device)
stopping_criteria5

[<__main__.create_stopping_criteria.<locals>.StoppingCriteriaSub at 0x7cc8ad807d60>]

In [25]:
time_1 = time()
query_pipeline = pipeline(
        "text-generation",
        model=model_name,
        tokenizer=tokenizer,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.001,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        torch_dtype=torch.float16, stopping_criteria=stopping_criteria5,
        device_map="auto",
        max_new_tokens=2048,min_length = 10)
time_2 = time()
print(f"Prepare pipeline: {round(time_2-time_1, 3)} sec.")

Prepare pipeline: 0.0 sec.


In [26]:
llm_hfp = HuggingFacePipeline(pipeline=query_pipeline)

In [27]:
#output = llm_hfp("Name one famous rock band.")
#print(output[0:20])

In [28]:
#output

# Prepare the SQLChain 

In [29]:
from langchain.prompts.prompt import PromptTemplate

_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer.\n Unless the user specifies in the question a specific number of examples to obtain, query for at most 5 results using the LIMIT clause as per SQLite. You can order the results to return the most informative data in the database.\nNever query for all columns from a table. You must query only the columns that are needed to answer the question. Pay attention to use only the column names you can see in the tables below. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.\nPay attention to use date('now') function to get the current date, if the question involves \"today\".
Use the following format:

Question: "Question here"
SQLQuery: "SQL Query to run"
SQLResult: "Result of the SQLQuery"

Only use the following tables:
{table_info}

If someone asks for the art table, they really mean the artworks table.

Only single quotation marks, not double quotation marks in the SQL statement (SQLQuery). Never use " in SQL statement (SQLQuery).

Question: {input}"""
PROMPT = PromptTemplate(
    input_variables=["input", "table_info", "dialect"], template=_DEFAULT_TEMPLATE
)

toolkit = SQLDatabaseToolkit(db=db, 
                             llm=llm_hfp)

agent_executor = create_sql_agent(
    llm=llm_hfp,
    toolkit=toolkit,
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,handle_parsing_errors=True
)

In [30]:
db.run("SELECT COUNT(*) FROM artists")

'[(15544,)]'

# Test the agent

In [31]:
QUESTION_01 = "How many artists are there?"
QUESTION_01a = "How many artists2 are there?"


In [32]:
question = "How many artists are there?"
#agent_executor.run(question)

In [33]:
question = "How many reviews are there?"
#agent_executor.run(question)

In [34]:
#!pip install langchain_experimental

In [35]:
from langchain_experimental.sql import SQLDatabaseChain

ModuleNotFoundError: No module named 'langchain_experimental'

In [ ]:
db_chain = SQLDatabaseChain.from_llm(llm_hfp,db,verbose = True,prompt=PROMPT,use_query_checker = True,return_intermediate_steps = False)

In [ ]:
db_chain

In [ ]:
db_chain(QUESTION_01)

In [ ]:
db_chain(QUESTION_01a)

In [ ]:
db_chain.run(QUESTION_01)

In [ ]:
1